#!/bin/bash
# Based on build_ncdf from Workshop 7


#### COMMAND LINE ARGS ####
# Can be modified to change system

problem="null"
nx=10
ny=10

#### COMPILE #### 

echo "Compiling Code"
# File dependancy chain
myprogramfiles="../src/command_line.f90 ../src/create_axis.f90 ../src/GlobalUtils.f90 ../src/FieldSolver.f90 ../src/ParticleSolver.f90 ../src/PIFWriter.f90 ../src/Main.f90"

#Name of compiled file
outfile="Sim_Memcheck.exe"

#Name of compiler
fc=gfortran
#Use nf-config to grab the compile and link flags. Backticks run command and grab output
fflags=`nf-config --fflags`
flibs=`nf-config --flibs`

#Compile Line
$fc -g -std=f2008 $fflags $myprogramfiles $flibs -o $outfile -g

#### EXECUTE COMPILED CODE ####
echo "Executing compiled code"
# Uses Command Line Args defined above
valgrind --leak-check=full ./$outfile nx=$nx ny=$ny problem=$problem > MemTest.txt

